config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
      resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  resources :categories, only: [:show]
  resources :products, only: [:show]

  get "admin" => "admin#index"
  get "cart" => "carts#show"
  post "checkout" => "checkouts#create"

  # Stripe checkout routes
  get 'checkout/success', to: 'checkouts#success'
  get 'checkout/cancel', to: 'checkouts#cancel'

  post '/webhooks', to: 'webhooks#stripe'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :medium, resize_to_limit: [250, 250]
  end

  belongs_to :category
  has_many :stocks
  has_many :order_products
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_admin_product, only: %i[ show edit update destroy ]

  # GET /admin/products or /admin/products.json
  def index
    if params[:query].present?
      @pagy, @admin_products = pagy(Product.where("name LIKE ?", "%#{params[:query]}%"))
    else
      @pagy, @admin_products = pagy(Product.all)
    end
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products or /admin/products.json
  def create
    @admin_product = Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_product_url(@admin_product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    @admin_product = Product.find(params[:id])
    if @admin_product.update(admin_product_params.reject { |k| k["images"] })
      if admin_product_params["images"]
        admin_product_params["images"].each do |image|
          @admin_product.images.attach(image)
        end
      end
      redirect_to admin_products_path, notice: "Product updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    @admin_product.destroy!

    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_product_params
      params.require(:product).permit(:name, :description, :price, :category_id, :active, images: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, admin_product], class: "contents") do |form| %>
  <% if admin_product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>
      <ul>
        <% admin_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <% if admin_product.images.any? %>
      <% admin_product.images.each do |image| %>
        <%= image_tag image, class: "w-20 h-20 object-cover rounded-md" %>
      <% end %>
    <% end %>
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.order(:name), :id, :name, id: "category", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <% if admin_product.persisted? %>
      <%= link_to "Product Stock", admin_product_stocks_path(admin_product), class: "underline", data: { turbo: false } %>
    <% else %>
      <span class="underline">To view stock, first save the product</span>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :active %>
    <%= form.check_box :active, class: "block mt-2 h-5 w-5" %>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= product.name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= product.description %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= product.price %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= product.category_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Active:</strong>
    <%= product.active %>
  </p>
  <% if action_name != "show" %>
    <%= link_to "Show this product", [:admin, product], class:"rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this product", edit_admin_product_path(product), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/admin/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>
  <%= render "form", admin_product: @admin_product %>
  <%= link_to "Show this product", [:admin, @admin_product], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Products</h1>
    <%= link_to "New product", new_admin_product_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="flex mt-4 flex-col md:flex-row items-start md:items-center justify-between w-full">
    <%= form_with url: admin_products_path, method: :get, class: "flex" do |form| %>
      <%= form.text_field :query, placeholder: "Search", class: "rounded border-gray-500 text-gray-800" %>
      <%= form.submit "Submit", class: "cursor-pointer bg-gray-500 ml-2 hover:bg-gray-600 text-white py-2 px-4 rounded" %>
    <% end %>
    <%= form_with url: admin_products_path, method: :get, class: "flex" do |form| %>
      <%= form.submit "Clear", class: "cursor-pointer bg-gray-500 ml-0 md:ml-2 mt-2 md:mt-0 hover:bg-gray-600 text-white py-2 px-4 rounded" %>
    <% end %>
  </div>

  <div class="flex flex-col w-full">
    <div class="overlow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overlow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Name
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Description 
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Price 
                </th>
              </tr>
            </thead>
            <tbody>
              <% @admin_products.each do |p| %>
                <tr class="bg-gray-50 border-b">
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
                    <% if p.images.any? %>
                      <% begin %>
                        <%= image_tag(p.images.first.variant(:thumb)) %>
                        <% rescue => e %>
                        Error: <%= e.message %>
                      <% end %>
                    <% else %>
                      <%= image_tag("https://via.placeholder.com/50") %>
                    <% end %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
                    <%= link_to p.name, edit_admin_product_path(p) %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
                    <%= p.description %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
                    $<%= (p.price/100.0).to_s %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", admin_product: @admin_product %>

  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_product %>

    <%= link_to "Edit this product", edit_admin_product_path(@admin_product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this admin_product", admin_product_path(@admin_product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>